### ISSUE TITLE
SinFest ERROR

### ISSUE THREAD

**Issue by momoe** [webcomics/dosage#100]
I tried installing and running dosage for Sinfest and got this reply.
`$ dosage SinFest
KeenSpot/SinFest> Retrieving 1 strip
KeenSpot/SinFest> ERROR: Patterns ['<img src=".+?(/comikaze/comics/.+?)"'] not found at URL http://www.sinfest.net/.
`

Please assist

**Comment by TobiX** [comment]
Is that with 2.15 or a current Git checkout? Because that should have been fixed already. Please reopen if the problem persists with a current version
