### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by grince** [webcomics/dosage#101]
Hi,

I received this internal error after updating dosage:

You have found an internal error in dosage. Please write a bug report
at https://github.com/webcomics/dosage/issues and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<class 'TypeError'> 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/foo/src/dosage/dosagelib/cmd.py", line 330, in main                                                                     
    res = run(options)                                                                                                                
  File "/home/foo/src/dosage/dosagelib/cmd.py", line 245, in run                                                                      
    return director.getComics(options)                                                                                                
  File "/home/foo/src/dosage/dosagelib/director.py", line 157, in getComics                                                           
    events.getHandler().start()                                                                                                       
  File "/home/foo/src/dosage/dosagelib/events.py", line 352, in start                                                                 
    handler.start()                                                                                                                   
  File "/home/foo/src/dosage/dosagelib/events.py", line 97, in start                                                                  
    self.rss = rss.parseFeed(self.rssfn, yesterday)                                                                                   
  File "/home/foo/src/dosage/dosagelib/rss.py", line 76, in parseFeed                                                                 
    content = getNode('channel')[0]  # Only one channel node                                                                          
TypeError: 'NoneType' object is not subscriptable                                                                                     
System info:                                                                                                                          
dosage 2.15.1.dev453                                                                                                                  
Python 3.5.3 (default, Jan 19 2017, 14:11:04)                                                                                         
[GCC 6.3.0 20170118] on linux                                                                                                         
Local time: 2018-01-04 10:28:18+002                                                                                               
sys.argv ['./dosage', '-o', 'rss', '--no-downscale', '-b', '/home/foo/webcomics/', '--adult', '--baseurl', '../', 'fooi', 'bar', [..] ]
LC_CTYPE = 'de_DE.UTF-8'
LANG = 'de_DE.UTF-8'

I already found one bug (easy to fix): in your documentation, you mention "rurl = escape(url)" in one line, but escape() doesn't exist anymore...

**Comment by TobiX** [comment]
You seem to have a broken `dailydose.rss` somewhere in your output directory and Python's rss parser cannot handle that...
