### ISSUE TITLE
GoComics are broken

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#102]
Currently, the GoComics scraper is broken.

`GoComics/AndyCapp> ERROR: XPath //div[@class="button-icon-group"]//a[contains(concat(" ", @class, " "), " fa-caret-left ")] not found at URL http://www.gocomics.com/andycapp.`

**Comment by hendersj** [comment]
I can confirm this - seems to have broken yesterday.

Using simonszu's comment, it looks like the line it's trying to match against is this one:

<a role="button" href="/andycapp/2018/03/20" class="fa btn btn-outline-default btn-circle fa-caret-left sm js-previous-comic " title="" data-unsp-sanitized="clean"></a>

**Comment by hendersj** [comment]
Looks like they removed the div with the button-icon-group class.  Changing the xpath to use `gc-calendar-nav__previous` might work if I'm reading this right.

**Comment by hendersj** [comment]
Not a clean fix, but this works:

`    navSearch = '//div[@class="gc-calendar-nav__previous"]//a[%s]'
    prevSearch = navSearch % xpath_class('fa-caret-left')
    navSearch = '//div[@class="gc-calendar-nav__next"]//a[%s]'
    nextSearch = navSearch % xpath_class('fa-caret-right')
`

Probably better to get rid of navSearch and just incorporate the full xpath into the prevSearch and nextSearch values.

**Comment by hendersj** [comment]
```
    prevSearch = '//div[@class="gc-calendar-nav__previous"]//a[%s]' % xpath_class('fa-caret-left')
    nextSearch = '//div[@class="gc-calendar-nav__next"]//a[%s]' % xpath_class('fa-caret-right')
```

Confirmed to work.  I'll fork and create a pull request for this as a fix (if I can work out how - haven't done that before)
