### ISSUE TITLE
Unsounded Broken

### ISSUE THREAD

**Issue by Dizhonoured** [webcomics/dosage#107]
`Unsounded> ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(http\\:\\/\\/www\\.casualvillain\\.com\\/Unsounded\\/comic/[^"]*)"[^>]*[^>]*><\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"http\\:\\/\\/www\\.casualvillain\\.com\\/Unsounded\\/images/newpages\\.png"[^>]*[^>]*>'] not found at URL http://www.casualvillain.com/Unsounded/.`

**Comment by TobiX** [comment]
Should be fixed. Tested against the last ~3 chapters, normal pages work, but there are some "special" pages which might be skipped...
