### ISSUE TITLE
Sally Forth, Safe Havens

### ISSUE THREAD

**Issue by littauer** [webcomics/dosage#110]
Apologies as I'm not yet git literate.

The following profiles inserted in dosagelib/plugins/s.py seem to work for the above strips.
They're patterned after Sherman's Lagoon, which is another KingFeatures strip
``
class SafeHavens(_BasicScraper):
    url = 'http://safehavenscomic.com/'
    stripUrl = url + 'comics/%s'
    firstStripUrl = stripUrl % '/june-28-1999/'
    imageSearch = compile(tagre("img", "src", r'(https://safr\.kingfeatures\.com/idn/cnfeed/zone/js/content\.php\?file=.+?)'))
    prevSearch = compile(r'id="previouscomic" class="button white"><a href="(%scomics/[a-z0-
9-]+/)"' % url)
    help = 'Index format: monthname-day-year'

    def namer(self, image_url, page_url):
        name = page_url.rsplit('/', 3)[2]
        if name == "safehavenscomic.com":
            name = datetime.date.today().strftime("%B-%d-%Y").lower()
        # name is monthname-day-year
        month, day, year = name.split('-')
        return "%s-%s-%s" % (year, month, day)

    
class SallyForth(_BasicScraper):
    url = 'http://sallyforth.com/'
    stripUrl = url + 'comics/%s'
    firstStripUrl = stripUrl % '/january-07-1996/'
    imageSearch = compile(tagre("img", "src", r'(https://safr\.kingfeatures\.com/idn/cnfeed/
zone/js/content\.php\?file=.+?)'))
    prevSearch = compile(r'id="previouscomic" class="button white"><a href="(%scomics/[a-z0-
9-]+/)"' % url)
    help = 'Index format: monthname-day-year'

    def namer(self, image_url, page_url):
        name = page_url.rsplit('/', 3)[2]
        if name == "sallyforth.com":
            name = datetime.date.today().strftime("%B-%d-%Y").lower()
        # name is monthname-day-year
        month, day, year = name.split('-')
        return "%s-%s-%s" % (year, month, day)

Thanks so much for a great product!

**Comment by hendersj** [comment]
This is actually very similar to my pull request #104 - at least for SallyForth - TobiX had a question about the use of namer() as a special case that I'm not sure how to answer - wonder if your Python experience could lend some help on that request to help me understand if that's needed or not.

My approach used another King Features comic as a starting point, but I found I had to introduce bounceStarter to get it to pull the dates right.  Do you find that your approach pulls more than one comic if you specify `-n 4` (for example) when running Dosage?

**Comment by littauer** [comment]
Both Sherman's Lagoon and Sally Forth work correctly with -n 4 (both #
strips and dates)
Maybe the strip you used as a base (OTFT) has a wrinkle the mainline
doesn't have. I've noticed in the past that the three Holbrook strips
(OTFT, SH, K&K) are a little odd and maybe not a good source for
cloning. Side Note: Safe Havens works fine for me with the code I
listed.
Maybe look at diffs between Shermans Lagoon & OTFT?
I haven't studied the code base either; just (luckily?) chose a good
source to clone for King Features strips.

**Comment by littauer** [comment]
Closed as all these strips are now part of ComicsKingdom.com (part of King Features) so these profiles are obsolete. I'm working on a generic scraper for them.

**Comment by hendersj** [comment]
Wanted to check back on this and see if there were any changes to this - I haven't noticed anything code-wise, but wondered if it was still on your radar.

**Comment by littauer** [comment]
See pull request # 134. This code has been working for me for several months now.

**Comment by hendersj** [comment]
Cool, thanks!

**Comment by hendersj** [comment]
I can confirm that this works here as well - all of the lower-resolution stuff from Arcamax works great on ComicsKingdom now as well.
