### ISSUE TITLE
ElGoonishShive and EGS-NP not working after URL formatting change

### ISSUE THREAD

**Issue by erpbridge** [webcomics/dosage#118]
El Goonish Shive and its sister comic, ElGoonishShiveNP, are throwing errors ever since a URL naming change that was instituted around May 25.  From the main comic:
old URL=http://egscomics.com/comic/2018-05-25
new URL=http://egscomics.com/comic/sister3-285

The new URL formatting seems to be holding true to current, sister3-310. It appears that naming will be based on current Storyline and numbering of comic in that storyline.

Errors thrown are as below:
ElGoonishShive> Retrieving all strips
ElGoonishShive> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(comics/[^"]+)"[^>]*comic[^>]*>'] not found at URL http://www.egscomics.com/.
ElGoonishShive> WARN: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/index\\.php\\?id=\\d+)"[^>]*prev[^>]*>'] not found at URL http://www.egscomics.com/. Assuming no previous comic strips exist.
ElGoonishShiveNP> Retrieving all strips
ElGoonishShiveNP> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(comics/[^"]+)"[^>]*comic[^>]*>'] not found at URL http://www.egscomics.com/egsnp.php.
ElGoonishShiveNP> WARN: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/egsnp\\.php\\?id=\\d+)"[^>]*prev[^>]*>'] not found at URL http://www.egscomics.com/egsnp.php. Assuming no previous comic strips exist.

**Comment by erpbridge** [comment]
It looks like it may be related to a problem with site owner's PHP incremental numbers.

http://www.egscomics.com/index.php?id=2501 shows a comic, May 21 2018.
http://www.egscomics.com/index.php?id=2502 shows the most recent comic, rather than the next comic for May 23 2018.

A similar problem exists for EGSNP…
http://egscomics.com/egsnp.php?id=771 shows the comic for May 21 2018
http://egscomics.com/egsnp.php?id=772 shows current comic (not the May 23 one)

**Comment by erpbridge** [comment]
This works for ElGoonishShive:
class ElGoonishShive(_ParserScraper):
    url = 'http://www.egscomics.com/'
    firstStripUrl = url + 'comic/2002-01-21'
    imageSearch = '//img[@id="cc-comic"]'
    prevSearch = '//a[@rel="prev"]'

**Comment by TobiX** [comment]
That's ComicControl, right?

https://github.com/webcomics/dosage/blob/master/dosagelib/plugins/common.py#L33-L35

**Comment by erpbridge** [comment]
Yeah, he uses that format. What I put in was my best effort not knowing all the workings of Dosage.

 

Emailed Shive, the comic artist, he said they did a site overhaul in May, and decided to stop using the ID numbering system going forward… they only left it for old comics.

**Comment by erpbridge** [comment]
I understand your point now.

Updated code as below in e.py. Added _ComicControlScraper in the from .common import. Tested locally, and it seems to work:

class ElGoonishShive(_ComicControlScraper):
    url = 'http://www.egscomics.com/'


class ElGoonishShiveNP(_ComicControlScraper):
    url = 'http://www.egscomics.com/egsnp.php'
