### ISSUE TITLE
Exiern - Previous Navi broken

### ISSUE THREAD

**Issue by erpbridge** [webcomics/dosage#119]
Exiern appears to have changed their Navi format, leading to the navi-prev to be broken (likely inherited from WPNavi as prevSearch is not defined in plugins\w.py). This leads to the following error:

Exiern> WARN: XPath //a[contains(concat(" ", @class, " "), " navi-prev ")] not found at URL http://www.exiern.com/. Assuming no previous comic strips exist.

**Comment by TobiX** [comment]
Should be fixed now. Testing isn't easy, since the websever seems to be overloaded most of the time...
