### ISSUE TITLE
Just created a snap for dosage

### ISSUE THREAD

**Issue by JohnBlood** [webcomics/dosage#125]
Hi,

I just finished creating a [snap](https://snapcraft.io/dosage) for dosage. It uses the git version of dosage,so some of the comic scrapers that are broken in the last release (ie Foxtrot) will work.

**Comment by TobiX** [comment]
Thanks a lot for maintaining the snap. If you want I can link from the README/homepage (You can also just send a pull request adding a link :smile_cat:)
