### ISSUE TITLE
Something Positive pre 2016

### ISSUE THREAD

**Issue by TahMahn** [webcomics/dosage#128]
Having some issues with Something Positive downloads from 2016 and earlier. I assume the issue lies in the way the site handles their "Previous Comic" links, changing it from a picture to just text sometime in 2016.

Im no expert though, just making assumptions based on what I could gleam from inspecting the site and fiddling with the scraper settings.

```class SomethingPositive(_BasicScraper):
    url = 'http://www.somethingpositive.net/'
    stripUrl = url + 'sp%s.shtml'
    imageSearch = (
        compile(tagre("img", "src", r'(sp\d+\.png)')),
        compile(tagre("img", "src", r'(twither\.gif)')),
    )
    prevSearch = compile(tagre("a", "href", r'(sp\d+\.shtml)') + 'Previous<br>Comic')
    help = 'Index format: mmddyyyy'
```

I've tried doing something this, changing the last part of **prevSearch** to "Previous Comic", "PreviousComic", "Previous", etc. 
Still, the previous comic search doesn't appear to work.

Any help would be most appreciated.

**Comment by TobiX** [comment]
I don't see any specific page where the layout changed in the history of that comic: The start page uses images, but all archive pages use plain text links. I updated the module to our modern parser, see if that helps. If not, reopen and show me a page which triggers your problem.
