### ISSUE TITLE
Blonde Sunrise Comic

### ISSUE THREAD

**Issue by rikere** [webcomics/dosage#142]
I have hit a snag getting Blonde Sunrise to work in Dosage. The site doesn't really use classes, and it's structured a little weird. The base URL leads to a static landing page. The comic is loaded via php script at /comic.php

If I use the comic's main URL for the URL option, everything breaks because the paths aren't right.

I've tried to use x-paths as well and that just crashes and burns too.

My two attempts so far:

```
 class BlondeSunrise(_ParserScraper):
     url = 'http://blondesunrise.com/comic.php?page=latest'
     firstStripUrl = 'http://blondesunrise.com/comic/comic.php?page=first'
     imageSearch = '//html/body/div/table/tbody/tr/td[2]/div/font/div/a/img'
     prevSearch = '//html/body/div/table/tbody/tr/td[2]/div/font/div/p/a[2]'



class BlondeSunrise(_BasicScraper):
    url = 'http://blondesunrise.com/'
    rurl = escape(url)
    stripUrl = url + 'comic_imgs/%s'
    firstStripUrl = 'http://blondesunrise.com/comic.php?page=first'
    imageSearch = compile(tagre("img", "src", r'(%scomic_imgs/[^"]+)' % rurl))
    prevSearch = prevSearch = compile(r'<a href="(.+?)".+previous.png')
    help = 'Index format: n (unpadded)'
```

Any help's appreciated.

**Comment by TobiX** [comment]
I added a version using nested XPath expressions
