### ISSUE TITLE
modulehelp indicates a comic supports index syntax, but error "object has no attribute 'path'" is thrown

### ISSUE THREAD

**Issue by DavidAccola** [webcomics/dosage#155]
Index syntax isn't working out when I try it, even when --modulehelp seems to indicate it will be supported for a comic. I'm trying to ape the examples found [here](https://wummel.github.io/dosage/dosage.1.html#index), but it could still just be something I'm doing wrong.

Example of issue:
![object has no attribute path](https://user-images.githubusercontent.com/62493194/77242057-878cbc00-6bc8-11ea-99fc-968aec3b215f.png)

**Comment by TobiX** [comment]
This seems to have been broken for at least 4 years, when the GoComics module was refactored to not have a path variable anymore :pensive: Unfortunately, there was no test to catch the error...
