### ISSUE TITLE
Outputting to log file

### ISSUE THREAD

**Issue by DavidAccola** [webcomics/dosage#164]
What method would you recommend for outputting the results of running dosage to a log file for later reference?

Context: I'm using Windows, for what it's worth. I have Windows Task Scheduler auto-run the file getcomics.bat every day, and my preference is to have the cmd window be as unintrusive as possible and auto-close as soon as dosage finishes running. But then I can't tell if there were errors. If I had a way to preserve the output of dosage, I'd be able to tell a lot more easily after the fact whether there were any comics dosage couldn't download.

Example: This is the batch file I run, getcomics.bat:
`start /min dosage --continue @ --output html --basepath C:\Comics\ --baseurl file:///C:/Comics/ --verbose`

I thought I'd just be able to add >>C:\Comics\log.txt, like this:
`start /min dosage --continue @ --output html --basepath C:\Comics\ --baseurl file:///C:/Comics/ --verbose >>C:\Comics\log.txt`
...but that just creates an empty log.txt file. It doesn't actually capture the "Retrieving 1 strip", etc.

Let me know if you have any ideas!

**Comment by TobiX** [comment]
That's just one of the gotchas when using the "start" tool, since it creates a new cmd session. You are just redirecting the output of "start", not of the started dosage process. Try wrapping the command in a cmd script or something similar.
