### ISSUE TITLE
Sequential Art site update broke scraper

### ISSUE THREAD

**Issue by MaddTheSane** [webcomics/dosage#167]
Sequential Art recently updated their website. As such, the Sequential Art scraper isn't working anymore:

    SequentialArt> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+[^>]*strip[^>]*\\s+[sS][rR][cC]\\s*=\\s*"([^"]+)"[^>]*[^>]*>'] not found at URL http://www.collectedcurios.com/sequentialart.php?s=926.

**Comment by sork-** [comment]
I can reproduce the bug.
