### ISSUE TITLE
Several sites are not properly being URL Decoded

### ISSUE THREAD

**Issue by bschollnick** [webcomics/dosage#168]
I can't track down the previous site, but I just tried running against sinfest.

SinFest> Skipping existing file "Comics/SinFest/2019-09-06.gif".
SinFest> Skipping existing file "Comics/SinFest/2019-09-05.gif".
SinFest> ERROR: Could not save image at http://www.sinfest.net/view.php?date=2019-09-04 to 2019-09-04: OSError('URL retrieval of http://www.sinfest.net/btphp/comics/2019-09-04.gif" alt= failed: 404 Client Error: Not Found for url: https://www.sinfest.net/btphp/comics/2019-09-04.gif%22%20alt=')
SinFest> ERROR: Could not save image at http://www.sinfest.net/view.php?date=2019-09-03 to 2019-09-03: OSError('URL retrieval of http://www.sinfest.net/btphp/comics/2019-09-03.gif" alt= failed: 404 Client Error: Not Found for url: https://www.sinfest.net/btphp/comics/2019-09-03.gif%22%20alt=')
SinFest> ERROR: Could not save image at http://www.sinfest.net/view.php?date=2019-09-02 to 2019-09-02: OSError('URL retrieval of http://www.sinfest.net/btphp/comics/2019-09-02.gif" alt= failed: 404 Client Error: Not Found for url: https://www.sinfest.net/btphp/comics/2019-09-02.gif%22%20alt=')

For some reason the closing " is being seen as a %22, instead of a quote character.

If I have a chance, I'll take a look and see if I see anything obvious.

But looking at the HTML, I don't see any obvious reason for this...

<img src="btphp/comics/2019-08-23.gif" alt="Royalty 38">

**Comment by TobiX** [comment]
Haha, the regex is matching too much. See https://regex101.com/r/pFnNCj/1 for an "explanation" what happens there...
