### ISSUE TITLE
throttling would be extremely useful. 

### ISSUE THREAD

**Issue by nerdguy1338** [webcomics/dosage#179]
Grrl Power blocks  downloading too many pages in a specified time. if i could  add an argument to sleep after each strip, that would probably fix it.

also, how do i run this from source?  ./dosage doesn't exist.

**Comment by Ruthalas** [comment]
I can answer your second question- This tool cannot be run from source without being 'installed'.
See [issue 145](https://github.com/webcomics/dosage/issues/145) for some information on that.

**Comment by TobiX** [comment]
Throttling is implemented, but probably needs some per-module fine-tuning. See for example:

https://github.com/webcomics/dosage/blob/e64635e86b2e2fa0efac36fb23a9507f472df859/dosagelib/plugins/comicsherpa.py#L16

**Comment by nerdguy1338** [comment]
Ok, thanks, but I've installed this as a pip module, how do I edit that
code?

**Comment by TobiX** [comment]
See the [README](https://github.com/webcomics/dosage#installation-for-development) (without the last sentence about the `dosage` script, that is deprecated) - You want to install dosage in "editable" mode, after that your git checkout is the "installed" version.

**Comment by nerdguy1338** [comment]
Ok thanks, I've got an editable version now, but I don't really understand
where the throttle code goes, I've tried just inserting it into the grrl
power class definition, but then it just pukes all over itself.
