### ISSUE TITLE
"This module needs the cssselect (python-cssselect) python module which is not installed" with cssselect installed

### ISSUE THREAD

**Issue by mathiasfoster** [webcomics/dosage#182]
I am trying the following command:
```
dosage --all GoblinsComic
```
Which fails with the following error:
```
MainThread> WARN: Skipping comic GoblinsComic: This module needs the cssselect (python-cssselect) python module which is not installed.
```
When I try:
```
pip install cssselect
# or
pip3 install cssselect
```
I get:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cssselect in ./.local/lib/python3.8/site-packages (1.1.0)
```

What further troubleshooting can I do to figure out where this issue is coming from?

**Comment by TobiX** [comment]
How did you install dosage in the first place? Maybe dosage is running under a different python version then the environment you installed cssselect in?

**Comment by mathiasfoster** [comment]
This problem was solved by removing the existing installation, and reinstalling dosage with:
```
pipx install dosage[css,bash]
```

**Comment by TobiX** [comment]
Very strange. I wonder if pipx updates might remove modules from the internal virtualenv...
