### ISSUE TITLE
ComicsKingdom site format seems to have changed

### ISSUE THREAD

**Issue by hendersj** [webcomics/dosage#205]
Follow-up to #204 - after overriding the SSL verification by adding the following line to http.py at line 47 (probably not the best way to do it, but it worked):

```
       kwargs['verify'] = False
```

I now get this message for a few comics I tried to pull:

```
./dosage ComicsKingdom/BeetleBailey ComicsKingdom/Bizarro ComicsKingdom/Blondie ComicsKingdom/Crankshaft ComicsKingdom/DennistheMenace ComicsKingdom/FamilyCircus ComicsKingdom/HagarTheHorrible ComicsKingdom/HiandLois ComicsKingdom/MotherGooseAndGrim ComicsKingdom/RhymesWithOrange ComicsKingdom/SallyForth
```

```
ComicsKingdom/[comic]> ERROR: Patterns [':is-left-arrow="true"[^>]*date-slug="(\\d\\d\\d\\d-\\d\\d-\\d\\d)"'] not found at URL https://www.comicskingdom.com/[path].
```
The above message shows for each of the comics identified in the command-line above.

It looks like the left arrow HTML now looks like this:

```
<img src="https://comicskingdom.com/wp-content/plugins/comicskingdom//img/icon_arrow_back.png" alt="Previous comic">
```
and the actual image appears as:

```
<div class="comic">
				<div id="theComicImage">

					
					<!-- desktop -->
					<img id="theComicImage" src="https://safr.kingfeatures.com/api/img.php?e=gif&amp;s=c&amp;file=U2FsbHlGb3J0aC8yMDIyLzAyL1NhbGx5X0ZvcnRoLjIwMjIwMjEyXzE1MzYuZ2lm" class="img-fluid ">

					<!-- mobile -->
									</div>
			</div>
```

Nice of them to find not just one way to break this, but two. :/

(Temporary workaround has been to change to Arcamax for all of these except Sally Forth, which isn't there; I added Hagar to Arcamax as well - so this can wait until KC gets their SSL certificate issues sorted out)

**Comment by pckizer** [comment]
Arcamax doesn't have all the same comics as CK, so in addition to dealing with the SSL cert, I have a tentative "working so far" local change to my install using this:

`--- comicskingdom.py       2022-02-14 08:34:11.910018000 -0600
+++ comicskingdom.py   2022-02-14 08:34:17.156267000 -0600
@@ -12,8 +12,8 @@

 class ComicsKingdom(_BasicScraper):
     imageSearch = re.compile(r'property="og:image" content="(https://[^"]*img\.php\?[^"]+)"')
-    prevSearch = re.compile(r':is-left-arrow="true"[^>]*date-slug="(\d\d\d\d-\d\d-\d\d)"')
-    nextSearch = re.compile(r':is-left-arrow="false"[^>]*date-slug="(\d\d\d\d-\d\d-\d\d)"')
+    prevSearch = re.compile(r'/(\d\d\d\d-\d\d-\d\d)"><[^>]* alt="Previous comic"')
+    nextSearch = re.compile(r'/(\d\d\d\d-\d\d-\d\d)"><[^>]* alt="Next comic"')
     starter = bounceStarter
     namer = joinPathPartsNamer((-2, -1), ())
     help = 'Index format: yyyy-mm-dd'
`

**Comment by hendersj** [comment]
Thanks, I'll give that a try later today.  Not only does Arcamax not have all the same comics as CK, the quality/size of the images is much lower as well.
