### ISSUE TITLE
Spinnerette does not load. 

### ISSUE THREAD

**Issue by jvanvinkenroye** [webcomics/dosage#21]
Module throws Error: Spinnerette> ERROR: Patterns ['<\s[iI][mM][gG]\s+(?:[^>]\s+)?[sS][rR][cC]\s=\s"(comics/[^"]+)"[^>]comic[^>]>'] not found at URL http://www.spinnyverse.com/.

The url of the newest strip is "http://www.spinnyverse.com/comics/1433333331-2015-06-03.jpg"

**Comment by Null000** [comment]
Thanks. I've fixed it. Pull/download the newest version to get the fix.
