### ISSUE TITLE
GoComics errors on first run max retries exceeded and 'EOF occurred in violation of protocol'

### ISSUE THREAD

**Issue by MrHappy** [webcomics/dosage#210]
Installed dosage and ran it for calvinandhobbes and immediately received this error:
`GoComics/CalvinAndHobbes> ERROR: URL retrieval of https://www.gocomics.com/calvinandhobbes failed: HTTPSConnectionPool(host='www.gocomics.com', port=443): Max retries exceeded with url: /calvinandhobbes (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
`
To make sure it wasn't anything on my machine/network/etc I also ran it for LeastICouldDo and that ran fine.
Is this related to #206 or something else/new?

**Comment by TobiX** [comment]
No idea, I cannot reproduce this issue.

**Comment by MrHappy** [comment]
Odd... Problem seems to has resolved itself...
