### ISSUE TITLE
GoblinsComic Not Working

### ISSUE THREAD

**Issue by kozinc** [webcomics/dosage#215]
Downloading failed with log:

`17:54:28 GoblinsComic> Retrieving 10 strips`
`17:54:28 GoblinsComic> Get strip URL http://www.goblinscomic.org/`
`17:54:29 GoblinsComic> ERROR: XPath #comic img not found at URL http://www.goblinscomic.org/.`
`17:54:29 GoblinsComic>   File "threading.py", line 890, in _bootstrap`
`17:54:29 GoblinsComic>   File "threading.py", line 926, in _bootstrap_inner`
`17:54:29 GoblinsComic>   File "dosagelib\director.py", line 82, in run`
`17:54:29 GoblinsComic>   File "dosagelib\director.py", line 96, in getStrips`
`17:54:29 GoblinsComic>   File "dosagelib\director.py", line 111, in _getStrips`
`17:54:29 GoblinsComic>   File "dosagelib\scraper.py", line 169, in getStrips`
`17:54:29 GoblinsComic>   File "dosagelib\scraper.py", line 188, in getStripsFor`
`17:54:29 GoblinsComic>   File "dosagelib\output.py", line 95, in exception`
`17:54:29 GoblinsComic>   File "dosagelib\scraper.py", line 125, in getComicStrip`
`17:54:29 GoblinsComic>   File "dosagelib\scraper.py", line 496, in fetchUrls`
`17:54:29 GoblinsComic> ValueError: XPath #comic img not found at URL http://www.goblinscomic.org/.`
`17:54:29 GoblinsComic> WARN: XPath .nav-previous > a not found at URL http://www.goblinscomic.org/. Assuming no previous comic strips exist.`

**Comment by kozinc** [comment]
Looks like the layout has changed; comic image id is #cc-comic, previous strip link is .cc-prev > a

**Comment by TobiX** [comment]
This was fixed with #153, which was merged after the last release (I really need to push out a new release sonnish...) - If you want to update to the current development versions, some ways are documented in the [README](https://github.com/webcomics/dosage#installation)
