### ISSUE TITLE
TheOrderOfTheStick Not Working

### ISSUE THREAD

**Issue by kozinc** [webcomics/dosage#220]
Downloading failed with log

`19:05:42 TheOrderOfTheStick> Retrieving 10 strips`
`19:05:42 TheOrderOfTheStick> Get strip URL http://www.giantitp.com/comics/oots1257.html`
`19:05:42 TheOrderOfTheStick> ERROR: Patterns ['<IMG src="(/comics/images/[^"]+)">'] not found at URL http://www.giantitp.com/comics/oots1257.html.`
`19:05:42 TheOrderOfTheStick>   File "threading.py", line 890, in _bootstrap`
`19:05:42 TheOrderOfTheStick>   File "threading.py", line 926, in _bootstrap_inner`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\director.py", line 82, in run`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\director.py", line 96, in getStrips`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\director.py", line 111, in _getStrips`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\scraper.py", line 169, in getStrips`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\scraper.py", line 188, in getStripsFor`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\output.py", line 95, in exception`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\scraper.py", line 125, in getComicStrip`
`19:05:42 TheOrderOfTheStick>   File "dosagelib\scraper.py", line 395, in fetchUrls`
`19:05:42 TheOrderOfTheStick> ValueError: Patterns ['<IMG src="(/comics/images/[^"]+)">'] not found at URL http://www.giantitp.com/comics/oots1257.html.`
`19:05:42 TheOrderOfTheStick> WARN: Patterns ['<A href="(/comics/oots\\d{4}\\.html)"><IMG src="/Images/redesign/ComicNav_Back.gif"'] not found at URL http://www.giantitp.com/comics/oots1257.html. Assuming no previous comic strips exist.`

**Comment by kozinc** [comment]
Strip image on page [http://www.giantitp.com/comics/oots1258.html](http://www.giantitp.com/comics/oots1258.html):
Looking through elements:
the image element:
`<img src="https://i.giantitp.com//comics/oots/oots1258_49d80b2d0cf9661e398ba113c62b7549.png">`
the link for the previous strip:
`<a href="oots1257.html"><img src="https://i.giantitp.com/redesign/ComicNav_Back.gif" alt="Previous Comic" title="Previous Comic" border="0"></a>`

Maybe the problem is the "https://i.giantitp.com/" part? Also, if it helps, I'm running release 2.17 on Windows 10.

**Comment by kozinc** [comment]
Tried it through the pipx installation rather than the dosage.exe and now it seems to work. Is it possible there's a difference in how the elements are being handled?

**Comment by TobiX** [comment]
No, it's just that 2.17 is now... over 2 years old and the comic has changed in the meantime... I'm not good at releasing stable versions *sigh* So this is already fixed in git...
