### ISSUE TITLE
how to update when installed with pipx?

### ISSUE THREAD

**Issue by MrHappy** [webcomics/dosage#224]
I installed dosage through pipx.
When I (try to) update dosage with `pipx install dosage` it says it is up2date.
However changes were added after latest package and they are not added on my system.
How can I get the latest updates or do I need to reinstall (and not use `pipx install/update dosage`?

**Comment by TobiX** [comment]
Just like updating any other software with pipx: `pipx upgrade dosage` or `pipx upgrade-all`

You can check the current version with `dosage --version` - if there were new commits, it should change after a pipx upgrade.

**Comment by MrHappy** [comment]
`dosage --version` gives me v2.17.
Which is the latest release (build feb 2020).
However the comics are not updated when I do `pipx update dosage` (I cannot see i.e.  'CSectionComics' in the comicslist.

**Comment by TobiX** [comment]
Yes, the last release is from 2020... There are instructions how to get the latest unstable version in the README
