### ISSUE TITLE
Remove pycountry dependency again...

### ISSUE THREAD

**Issue by TobiX** [webcomics/dosage#23]
In 86b31dc12b8938655535320417831b647e62ee57 I replaced the static language list with the "correct" dependency to pycountry. The problem is that

- pycountry is ~ 30 MB big, which is quite heavy for "just" language names
- pycountry is not zip-save, this complicates building a single-file .exe for Windows

I probably go ahead and revert most of 86b31dc12b8938655535320417831b647e62ee57 or just use pycountry at runtime if it is already installed, falling back to a minimal internal list. Other ideas?

**Comment by Null000** [comment]
Sounds good.

**Comment by Manabi** [comment]
I think keeping just the minimal internal list is good enough for this.  30MB for just language names is a bit much.
