### ISSUE TITLE
Downloads for Arcamax strips failing with SSL errors when using dosage.exe

### ISSUE THREAD

**Issue by ladewig** [webcomics/dosage#233]
I am using dosage.exe v3.0 and downloads for Arcamax strips started failing with SSL errors on September 27. The error for TakeItFromTheTinkersons is listed below.

`ERROR: Could not save image at http://www.arcamax.com/thefunnies/takeitfromthetinkersons/ to 2350700: SSLError(MaxRetryError("HTTPSConnectionPool(host='resources.arcamax.com', port=443): Max retries exceeded with url: /newspics/235/23507/2350700.gif (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))"))`

Looking at the cert for resources.arcamax.com shows it was issued on September 27.

**Comment by TobiX** [comment]
Yeah, they fucked up their certificate setup, the certificate chain is actually incomplete, which you won't notice most of the time when using a web browser, since browsers cache intermediate certificates (You might be able to see the error with a fresh browser profile, though)

See: https://www.ssllabs.com/ssltest/analyze.html?d=resources.arcamax.com

**Comment by ladewig** [comment]
Might be helpful to have a command line option for the exe to skip SSL validation for downloads as a workaround when one of the sites messes up until they get it fixed.

**Comment by TobiX** [comment]
I have implemented a much sadder workaround already for another site: https://github.com/webcomics/dosage/commit/5ee888d8890e19dee70f1684e34ab4b3a3d9332d - Will probably add the same for Arcamax :man_shrugging:

**Comment by littauer** [comment]
All of the Arcamax strips I followed are also available on ComicsKingdom effective with 3.0.

Don't stop a fix for Arcamax, but maybe it can relieve some pressure.

**Comment by TobiX** [comment]
This seems to be working nowadays, closing.
