### ISSUE TITLE
Locked thread with SluggyFreelance

### ISSUE THREAD

**Issue by kierun** [webcomics/dosage#241]
When I ran my script to get all the comics I read, I got it to hang for 30 mins. I used `ctrl+C` to break out and this is what I got:

```bash
SluggyFreelance> Skipping existing file "Comics/SluggyFreelance/201208e.png".

^CMainThread> WARN: Interrupted! Waiting for download threads to finish.
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

I could be SluggyFreelance's fault, or it could be SomethingPositive as that is coming next in the list.

What else can I do to help debug this?

**Comment by erpbridge** [comment]
Check to see if this is still happening after you do a git update for current dosagelib plugin s.py. Introduced a pull request that was merged into Dosage 26-Nov that changed Sluggy from http to https, as all content is now hosted on https. That may potentially have no impact on your issue, but was a change nonetheless.

**Comment by kierun** [comment]
@erpbridge Thank you. I will report tomorrow.

**Comment by kierun** [comment]
It seemed to have fixed that one. I am still getting numerous archives for each Monday. I guess that's another bug.

**Comment by TobiX** [comment]
I think (to be tested) we don't configure any connection timeouts, so a hanging TCP connection will lock up Dosage 🤔
