### ISSUE TITLE
New Comics Assistance: GPF-Comics, cad-comic

### ISSUE THREAD

**Issue by erpbridge** [webcomics/dosage#242]
Hi,

I attempted to write some custom plugins for a couple comics, but I'm running into some problems. Hoping you can give some suggestions. 

-For GPF,  I get a 403 Client error. 
ERROR: Could not save image at https://gpf-comics.com/ to gpf20221111JnE3W: HTTPError('403 Client Error: Access Forbidden for url: https://www.gpf-comics.com/comics/gpf20221111JnE3W.png'). Not sure what might be happening, other than maybe Dosage uses a User Agent String that GPF blocks... but thats a wild guess with no backing. 
-For CAD-Comic, they use a WordPress backend... but have some URL rewriter that makes every page present as cad-comic/# . Because of this, dosage downloads the image on the main page, clicks prevSearch, and then... says its already been to that page. Which, rightfully, it has. Have you run across any other pages that have similar situation, and found an answer?

My attempted plugin code. Its got too may imports, I know.. but figured better safe during development.

```
# SPDX-License-Identifier: MIT
# Copyright (C) 2004-2008 Tristan Seligmann and Jonathan Jacobs
# Copyright (C) 2012-2014 Bastian Kleineidam
# Copyright (C) 2015-2022 Tobias Gruetzmacher
# Copyright (C) 2019-2020 Daniel Ring
from re import compile, escape
from typing import List

from ..scraper import _BasicScraper, _ParserScraper
from ..helpers import bounceStarter, indirectStarter, joinPathPartsNamer
from ..util import tagre
from .common import ComicControlScraper, WordPressScraper, WordPressNavi, WordPressWebcomic

class GeneralProtectionFault(_ParserScraper):
    url = 'https://gpf-comics.com/'
    stripUrl = url + 'archive/%s'
    firstStripUrl = stripUrl + 'archive/1998/11/02'
    imageSearch = '//img[contains(@src, "/comics/gpf")]'
    prevSearch = '//a[./img[@alt="Previous Comic"]]'

class CadComic(WordPressWebcomic):
    url = 'https://Cad-Comic.com/'
    stripUrl = url + 'comic/%s'
    firstStripUrl = stripUrl + 'comic/nice-melon'
    imageSearch = '//img[@class="comic-display"]'
    prevSearch = '//a[@class="previous-post-link"]'
```

Error messages

```
C:\dosage>dosage GeneralProtectionFault -b c:\temp\gpf -v
GeneralProtectionFault> Retrieving 1 strip
GeneralProtectionFault> Get strip URL https://gpf-comics.com/
GeneralProtectionFault> Get image URL https://gpf-comics.com/comics/gpf20221111JnE3W.png
GeneralProtectionFault> ERROR: Could not save image at https://gpf-comics.com/ to gpf20221111JnE3W: HTTPError('403 Client Error: Access Forbidden for url: https://www.gpf-comics.com/comics/gpf20221111JnE3W.png')
GeneralProtectionFault>   File "threading.py", line 966, in _bootstrap
GeneralProtectionFault>   File "threading.py", line 1009, in _bootstrap_inner
GeneralProtectionFault>   File "dosagelib\director.py", line 82, in run
GeneralProtectionFault>     self.getStrips(scraperobj)
GeneralProtectionFault>   File "dosagelib\director.py", line 96, in getStrips
GeneralProtectionFault>     self._getStrips(scraperobj)
GeneralProtectionFault>   File "dosagelib\director.py", line 112, in _getStrips
GeneralProtectionFault>     skipped = self.saveComicStrip(strip)
GeneralProtectionFault>   File "dosagelib\director.py", line 142, in saveComicStrip
GeneralProtectionFault>     out.exception('Could not save image at {} to {}: {!r}'.format(
GeneralProtectionFault>   File "dosagelib\output.py", line 77, in exception
GeneralProtectionFault>     self.writelines(traceback.format_stack(), 1)
GeneralProtectionFault>   File "dosagelib\comic.py", line 102, in save
GeneralProtectionFault>     self.connect()
GeneralProtectionFault>   File "dosagelib\comic.py", line 65, in connect
GeneralProtectionFault>     self.urlobj = urlopen(self.url, self.scraper.session,
GeneralProtectionFault>   File "dosagelib\util.py", line 251, in urlopen
GeneralProtectionFault>     req.raise_for_status()
GeneralProtectionFault>   File "requests\models.py", line 960, in raise_for_status
GeneralProtectionFault> requests.exceptions.HTTPError: 403 Client Error: Access Forbidden for url: https://www.gpf-comics.com/comics/gpf20221111JnE3W.png
```

```
C:\dosage>dosage CadComic -b c:\temp\cad -a -v
CadComic> Retrieving all strips
CadComic> Get strip URL https://Cad-Comic.com/
CadComic> Get image URL https://cad-comic.com/wp-content/uploads/2022/11/Strip20221111a.x68566.png
CadComic> Skipping existing file "c:\temp\cad\CadComic\Strip20221111a.x68566.png".
CadComic> WARN: Already seen previous URL 'https://Cad-Comic.com/'
```

**Comment by TobiX** [comment]
GPF has been actively blocking Dosage since at least 2016 and I won't accept any contribution of a new module circumventing this block. See the error message you get when fetching with a Dosage user agent:
> If you are using a comic fetching script to scrape our site and download comics... stop it. No, really. We mean it. If this is the case and you're receiving this error, then we have explicitly blocked either your scraping tool or - worse - your IP address, and we're not going to remove that block until you've demonstrated that you're not going to do it again. ["Bandwidth bandits" will not be tolerated.](https://www.gpf-comics.com/faq.php#bandwidthbandit)

**Comment by erpbridge** [comment]
Thank you. I tried to look through Issues, missed seeing this one.

**Comment by erpbridge** [comment]
Query: Would there be any appetite for doing a pull of this comic via Archive.org? I have a successfully tested class that was able to do this, without touching the production GPF site.

**Comment by TobiX** [comment]
I'd rather not. I'm trying to keep Dosage as much as a "good web citizen" as possible (a bit in the spirit of youtube-dl and similar tools). This is why Dosage respects robots.txt files and removes modules on request of the author (even if that hasn't happened yet). I obviously cannot stop you from modifying your local copy of Dosage to disable these restrictions or add extra plugins into the user plugin directory (You can query the user plugin directory by running `dosage --version -vv`)

**Comment by erpbridge** [comment]
Fair enough. Based on all above, closing issue.
