### ISSUE TITLE
changed from wummel/dosage-2.15 to webcomics/dosage; but still MGG issue

### ISSUE THREAD

**Issue by eikelan** [webcomics/dosage#26]
Thank you for the dosage fork!
Deinstalled dosage-2.15 package of Debian testing.
Installed dosage-master
Installed python-setuptools
Now Dilbert and KevinAndKell download correctly and show up in the resulting html file.

Still MotherGooseAndGrimm does not work, however.

Checking out my dosage manually:

$ dosage MotherGooseandGrimm:2015-07-20
Arcamax/MotherGooseAndGrimm> Retrieving 1 strip for index 2015-07-20
Arcamax/MotherGooseAndGrimm> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[dD][aA][tT][aA][--][zZ][oO][oO][mM][--][iI][mM][aA][gG][eE]\\s*=\\s*"(/newspics/[^"]+)"[^>]*[^>]*>'] not found at URL http://www.arcamax.com/thefunnies/mothergooseandgrimm/2015-07-20.

Not life-threatening but would be nice to have.
Thanks again and greetings
Eike, Paraguay

**Comment by Null000** [comment]
Could you try
dosage MotherGooseandGrimm

Seems like the url format changed and the ability to get the comic for a certain date is now broken. Getting the latest comic (or comics in order) seems to work fine.

**Comment by eikelan** [comment]
Thank you!
That worked.
