### ISSUE TITLE
Not installable on editable mode

### ISSUE THREAD

**Issue by Typhonragewind** [webcomics/dosage#266]
I'm trying to install dosage in editable mode to hopefully contribute some new comic classes to it, but i keep getting this error:

ERROR: Project file:///repos/dosage has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

I'm not at all familiar with build backends, do you have any advice?

**Comment by Typhonragewind** [comment]
Was able to do it using pipx instead of pip, sorry for the trouble.

**Comment by TobiX** [comment]
AFAICS, setuptools has had support for PEP-660-style editable mode since [v64.0.0](https://setuptools.pypa.io/en/latest/history.html#v64-0-0), so a modern pip (newer 21.1, maybe?) paired with a modern setuptools should net you a working editable install.

**Comment by Typhonragewind** [comment]
It still gave me the error on pip v22.0.2 though
