### ISSUE TITLE
Added custom Webtoon comic; only downloaded 6 images? (MacOS)

### ISSUE THREAD

**Issue by GittyGharial** [webcomics/dosage#276]
I'm trying to add a WebToon comic that isn't currently supported (Crow Time), following the official documentation: (https://dosage.rocks/doc/adding_new_comics/). According to output of `dosage --help`, my plugins directory should be in ~/Library/Application Support/dosage/plugins; however dosage/plugins does not exist in ~/Library/Application Support.  I found a plugins folder in ~/opt/miniconda3/lib/python3.9/site-packages/dosagelib/plugins/ and edited webtoons.py with a single line change: Underneath line 120, `cls('CookingComically', 'tiptoon/cooking-comically', 622),`, I added: `cls('CrowTime', 'challenge/crow-time', 693372),`, getting the values from the patterns in the urls of the others (https://www.webtoons.com/en/tiptoon/cooking-comically/list?title_no=622) you can see where the values come from, similarly, https://www.webtoons.com/en/challenge/crow-time/list?title_no=693372)

After doing that, Crow Time shows up in dosage --list as "WebToons/CrowTime", and it downloads, but it only downloads 6 images.  In fact, those 6 images come from the latest release (https://www.webtoons.com/en/challenge/crow-time/some-doodles-1/viewer?title_no=693372&episode_no=103).  Meanwhile, I was hoping to download every image of every release, ordered in chronological order from oldest to newest.

I've presented a couple problems here and I'd appreciate any help getting me pointed in the right direction.  Thank you!

**Comment by TobiX** [comment]
>  however dosage/plugins does not exist in ~/Library/Application Support. 

That's normal. You have to create it if you want to use that directory

> found a plugins folder in ~/opt/miniconda3/lib/python3.9/site-packages/dosagelib/plugins/ and edited webtoons.py 

Sure, you can do that, but your change will be gone as soon as you update Dosage

> but it only downloads 6 images

The default for Dosage is always to only download the latest page. Use `-n NUMSTRIPS`, `-a` or `-c` to change that behavior. 

Since the comic works for me, I went ahead and added it.

**Comment by GittyGharial** [comment]
Thank you!

I'm new to participating in GitHub (though we use git at work); is there a way for me to get the latest changes?  I tried `pip install dosage --upgrade` but it said I was up to date.  I thought maybe I could just just clone the repo and git pull from master instead, then run dosage within that repo, but I don't see any dosage.sh.  I must be missing a step here.

**Comment by TobiX** [comment]
No idea what's the right way on macOS (with conda?), but most if the time I'd suggest using [pipx](https://pypa.github.io/pipx/) for installation. If you want to run from master, follow either the instructions for that [in the installation chapter of the README](https://github.com/webcomics/dosage#install-with-pipx) or use the instructions for [installation for development](https://github.com/webcomics/dosage#installation-for-development) if you want to be able to edit stuff right from the checkout.

**Comment by GittyGharial** [comment]
Alright, I installed with `pipx install --force "dosage[css,bash] @ git+https://github.com/webcomics/dosage.git"` (the --force is because I had an existing installation of dosage already and needed to force it to install the dev version over it). I then typed 
`dosage --version' and got "Dosage 3.0" as the output.  Is 3.0 the latest dev version?
