### ISSUE TITLE
Broken Webcomic

### ISSUE THREAD

**Issue by grince** [webcomics/dosage#277]
Hi,
some webcomics - especially Scandinavia and the World, Girls with Slingshots and LittleGamers seem have changed their website so that diosage can not use them anymore.
is there a way to fix it?

**Comment by TobiX** [comment]
You can either fix it yourself and open a pull request or notify me by creating issues. When creating issues, please clearly state which comics are broken, ideally with error output. Try to restrict reports to one comic per issue, this makes it easier to mark issues as fixed.
