### ISSUE TITLE
TheWhiteboard - Page retrieval not working

### ISSUE THREAD

**Issue by dmoonfire** [webcomics/dosage#279]
I was trying to download TheWhiteboard and got this error:

```
TheWhiteboard> Retrieving 1 strip
TheWhiteboard> ERROR: list index out of range
```

I'm not entirely sure how to investigate this one, sorry. Looking at the code, it seems right but I'm not sure where it is failing.

**Comment by TobiX** [comment]
Hmm, I cannot reproduce this problem. Can you run with increased verbosity (Add `-v` a couple of times) to get a stack trace?

**Comment by dmoonfire** [comment]
Thank you.

```
dosage --all TheWhiteboard -vvvv >& TheWhiteboard.txt
```

[TheWhiteboard.txt](https://github.com/webcomics/dosage/files/12445815/TheWhiteboard.txt)

**Comment by TobiX** [comment]
Uhm. Dosage 2.17? That's over 3 years old (2020-02-02), could you retry with either the current release or (even better) the latest git version? This has probably been fixed already.

**Comment by dmoonfire** [comment]
I didn't realize Nix unstable was so grievously out of date. It looks like 3.0 solves that problem, so I'll work on getting an updated package first.

My apologizes.
