### ISSUE TITLE
Flipside comic moved

### ISSUE THREAD

**Issue by ShaBangBinBash** [webcomics/dosage#283]
Used to be http://flipside.keenspot.com/
Is now https://www.flipsidecomics.com/
line 93 in the f.py plugin

**Comment by DDzwiedziu** [comment]
I've just discovered dosage and semi-randomly tried this comic. `dosage` downloads the last page (`keenspot-endpage.gif`) from Keenspot instead the new site.

Version 3.0 installed via `pipx`.
