### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.urllib3'

### ISSUE THREAD

**Issue by MrHappy** [webcomics/dosage#290]
My system crashed and I wanted to reinstall dosage.
Got the most recent image for my pi, flashed and updated it.
When I run `pipx install "dosage[css,bash] @ git+https://github.com/webcomics/dosage.git"`   I get the following error
```
from pip._vendor.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.urllib3'
'/home/pi/.local/pipx/venvs/dosage[css,bash] @ git+https:/github.com/webcomics/dosage.git/bin/python -m pip install --upgrade pip -q' failed
```
I reinstalled python and pip, but the error remains.
It is probably something simple, but I can't find it..
Anyone can help me out?

**Comment by TobiX** [comment]
You probably broke either your Python, pip or pipx installation.

1. Make sure no local installation of pip or pipx exist in `~/bin` or `~/.local/bin`
2. Make sure no user-installed Python modules mess with your system Python installation, for example in `/usr/local/lib/python*` or `~/.local/lib/python`
3. Reinstall the system pip & pipx if you suspect you might have damaged it previously (for example with `sudo pip`): `apt reinstall python3.11-venv python3-pip-whl python3-pip pipx`
4. Maybe reinstall all pipx-installed things with `pipx reinstall-all` if it isn't pipx that's broken, but any of the tools installed with it.

Anyways, this isn't a Dosage issue, so you should probably ask either in the forum of your distro or the pipx project. Good luck!

**Comment by TobiX** [comment]
The general "I-borked-my-pip" debugging guide is here: https://github.com/pypa/pip/issues/5599
