### ISSUE TITLE
dosage fails to run: rpath/libxslt.1.dylib image not found

### ISSUE THREAD

**Issue by GittyGharial** [webcomics/dosage#297]
Had to uninstall and reinstall dosage.  I used pipx: 
`pipx install --force "dosage[css,bash] @ git+https://github.com/webcomics/dosage.git"`
When I ran dosage, I got this error:

```
Traceback (most recent call last):
  File "~/.local/bin/dosage", line 5, in <module>
    from dosagelib.cmd import main
  File "~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/dosagelib/cmd.py", line 17, in <module>
    from . import events, configuration, singleton, director
  File "~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/dosagelib/director.py", line 15, in <module>
    from .scraper import scrapers as scrapercache
  File "~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/dosagelib/scraper.py", line 15, in <module>
    from lxml.html.defs import link_attrs as lxml_link_attrs
  File "~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: dlopen(~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/lxml/etree.cpython-311-darwin.so, 2): Library not loaded: @rpath/libxslt.1.dylib
  Referenced from: ~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/lxml/etree.cpython-311-darwin.so
  Reason: image not found
```

**Comment by TobiX** [comment]
I have no idea how binary wheels work on macOS... Maybe ask the `lxml` project for help? It looks like a broken wheel to me (at first glance)...

**Comment by TobiX** [comment]
Closing du to missing feedback and I see nothing that can be done in Dosage to fix this. Feel free to reopen if you think this is still an issue.

**Comment by GittyGharial** [comment]
Sorry, I should have closed this myself.  The issue was unrelated to dosage and had to do with a custom thing in my bashrc for another package.  They handle dylib in conflicting ways, so if I want to use one tool or the other I have to configure them for the specific tool.  If anyone stumbles upon this and uses ImageMagick and has conflicts, look at your bashrc.
