### ISSUE TITLE
-o json doesn't write image names out if it skips the image

### ISSUE THREAD

**Issue by garbled1** [webcomics/dosage#302]
Trying to build the json file, but I already have the strips downloaded.  It seems to know the filenames, so why isn't it loading it into the json file?

(venv) wcdl@media-dl:/comics/hold/broke$ dosage -v -n 10 -b /comics/hold/broke Replay -o json
Replay> Retrieving 10 strips
Replay> Get strip URL https://replaycomic.com/comic/iv-94/
Replay> Get image URL https://i2.wp.com/replaycomic.com/wp-content/uploads/2024/02/94.png?fit=800%2C1132&quality=100&strip=all&ssl=1
Replay> Skipping existing file "/comics/hold/broke/Replay/4-94-iv-94.png".
Replay> Get strip URL https://replaycomic.com/comic/iv-93/
Replay> Get image URL https://i1.wp.com/replaycomic.com/wp-content/uploads/2024/02/93.png?fit=800%2C1132&quality=100&strip=all&ssl=1
Replay> Skipping existing file "/comics/hold/broke/Replay/4-93-iv-93.png".
Replay> Get strip URL https://replaycomic.com/comic/iv-92/
Replay> Get image URL https://i0.wp.com/replaycomic.com/wp-content/uploads/2024/01/92.png?fit=800%2C1132&quality=100&strip=all&ssl=1
Replay> Skipping existing file "/comics/hold/broke/Replay/4-92-iv-92.png".

```  
  "https://replaycomic.com/comic/iv-94/": {
      "images": {},
      "prev": "https://replaycomic.com/comic/iv-93/"
    },
```

**Comment by TobiX** [comment]
Yes, this is a long-standing issue with the json output. See #49
