### ISSUE TITLE
ComicsKingdom is failing to download named comics

### ISSUE THREAD

**Issue by hendersj** [webcomics/dosage#314]
As of today, everything seems to download "Beetle Moses".  Attached is a log showing just the affected comics in my list.
[beetlemoses.txt](https://github.com/webcomics/dosage/files/15281441/beetlemoses.txt)

**Comment by hendersj** [comment]
Today's run just attempted to retrieve the same ones as yesterday, FWIW - and since they already existed, no additional downloads happened.

**Comment by TobiX** [comment]
*sigh* Their pages are pretty tricky to navigate through... Let's see if I get it to at least stay on the correct comic at all times... (even if it breaks in the future)

**Comment by hendersj** [comment]
Thanks for the quick fix - my testing shows that seems to work.  If I see any issues in the coming days, I'll let you know.
