### ISSUE TITLE
Add comic General Protection Fault

### ISSUE THREAD

**Issue by scouchman** [webcomics/dosage#319]
Request to add General Protection Fault, also known as GPF

https://www.gpf-comics.com/

(Sorry, I'm trying to learn how to do these and also help submit changes, I tried to do GPF and am not getting it to work)

**Comment by TobiX** [comment]
GPF is actively blocking dosage with a reference to https://www.gpf-comics.com/faq.php#bandwidthbandit, so I won't add it again. (Previously: #176 #242)
