### ISSUE TITLE
Add How to be a mind reaver from WebToons.

### ISSUE THREAD

**Issue by kierun** [webcomics/dosage#321]
[Source](https://www.webtoons.com/en/canvas/how-to-be-a-mind-reaver/list?title_no=301213)

If it is as simple as editing `dosagelib/plugins/webtoons.py`, then I can submit a patch. However, I suspect there might be more work involved. Do let me know if you want a hand.

Ditto for [Mage and Mimic](https://github.com/webcomics/dosage/issues/320).

**Comment by TobiX** [comment]
Yeah, since the Webtoons site is very uniform, just adding the correct line is enough.

**Comment by kierun** [comment]
@TobiX Thank you so much! I now feel super lazy when I could have submitted a PR… Next time!
