### ISSUE TITLE
WebToons timeout error? Returning ERROR: Document is empty

### ISSUE THREAD

**Issue by GittyGharial** [webcomics/dosage#325]
I'm using dosage 3.1.dev161+g2b7ca3f, the latest pipx dev branch release at this time.
I tried to update a webtoon I haven't read in a while.  It downloaded some comics and then failed out with this error:

`ERROR: Document is empty`

I moved the folder out of my working directory and tried to download the entire set. It failed again with that error, but on a *different* number of strip.  

Based on this I think dosage's requests are triggering some sort of timeout or rate limiting error.  I do not have the dev code to check, but I've written some custom webscraping scripts myself and dealt with similar issues where it works for several images and then gets blocked.  Typically an exponential retry backoff strategy has handled those cases well, and I can recommend that as a possible solution to this issue if it hasn't already been implemented.

Here's a sloppy example:

```
import os
import sys
import requests
from bs4 import BeautifulSoup
from PIL import Image
from io import BytesIO
from urllib.parse import urljoin
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

os.chdir('~/workingdir/comic/')

url_root = "https://content/pages"

numbers_list = [str(i).zfill(3) for i in range(firstpage, lastpageplusone)] 


# Use a retry mechanism with timeout
retry_strategy = Retry(
    total=3,  # Number of retries
    backoff_factor=2,  # Exponential backoff factor
    status_forcelist=[429, 500, 502, 503, 504],  # Retry on these status codes
)

adapter = HTTPAdapter(max_retries=retry_strategy)

# Set a timeout for the entire session
timeout = 10  # Set your desired timeout in seconds

with requests.Session() as session:
    session.mount('http://', adapter)
      session.mount('https://', adapter)

    # Set timeout for the entire session
    session.timeout = timeout

    for el in numbers_list:
        img_url = f"{url_root}{el}.png"
            
        image_data = requests.get(img_url).content
        image_save_file = f"{el}.png"
        
        with open(image_save_file, 'wb') as image_writer:
            image_writer.write(image_data)
```

**Comment by TobiX** [comment]
There is already a system for delays between downloads in place:
https://github.com/webcomics/dosage/blob/2b7ca3f30ccf2b3b4d1c9c41cc0b3363ec2fdf15/dosagelib/http.py#L26-L32
(As you can see in the same file, retries and exponential backoff is alrady configured)

You can add a throttle in the __init__ method of a comic module, like this:
https://github.com/webcomics/dosage/blob/2b7ca3f30ccf2b3b4d1c9c41cc0b3363ec2fdf15/dosagelib/plugins/g.py#L115

You might want to play around with this a bit... From experience I can say it's better to delay **before** running into any limits, because some hosters throttle very hard if you cross some threshold just once...

**Comment by GittyGharial** [comment]
Thank you, that worked perfectly!

If anyone else finds this ticket, here's a step by step:

Go to ~/.local/pipx/venvs/dosage/lib/python3.11/site-packages/dosagelib/plugins

Then in webtoons.py there's class WebToons.  I just added `self.session.add_throttle('webtoons.com', 1.0, 1.5) # adding a throttle timer` right under 
`    def __init__(self, name: str, path: str, titlenum: int):
        super().__init__('WebToons/' + name)`
        
And now the timeout issue is solved.
