### ISSUE TITLE
Derideal module needs updating

### ISSUE THREAD

**Issue by MaddTheSane** [webcomics/dosage#330]
It looks like https://derideal.com has updated its web-site so the current scraper doesn't work. It also is missing "Lost Memories" and "Xeno Experiments Nova" sub-comics.

Also, although the comic is available in Spanish, there doesn't seem to be a way for Dosage to download the Spanish comics.

**Comment by TobiX** [comment]
Meh, someone wanted to be too clever when writing the initial module. I'm reworking it to be quite a bit simpler (and hopefully break less often), but the image naming changed in the process...
