### ISSUE TITLE
Renaming comics

### ISSUE THREAD

**Issue by TobiX** [webcomics/dosage#41]
It should be possible to rename comic modules and somehow keep the old name around to redirect users of the old module to the new module...

We could put those into a special "deprecated" module, so it's easy to remove them later.

We might also do this for modules that once where part of Dosage, but are removed later (site disappeared, comic was deleted, crawling is now blocked), so we can inform user about the reason why we don't support her favorite module anymore.

**Comment by Null000** [comment]
I like the idea.

My only suggestion would be to not have the modules for renames around forever, but to add "Please migrate by X" in the message.

**Comment by TobiX** [comment]
I implemented this idea just now. Some "reasons" might be wrong and I probably missed some renames. If someone wants to check these, please send pull requests :wink:
