### ISSUE TITLE
version 2.15 not working on windows

### ISSUE THREAD

**Issue by dbb1480** [webcomics/dosage#43]
Not sure if this is the right place to log this.

Tried installing .exe and the script itself.  When .exe is installed and running any dosage command get error of 

  File "dosage", line 18, in <module>
  File "dosagelib\events.pyo", line 11, in <module>
  File "dosagelib\util.pyo", line 17, in <module>
  File "requests__init__.pyo", line 58, in <module>
  File "requests\utils.pyo", line 25, in <module>
  File "requests\compat.pyo", line 7, in <module>
  File "requests\packages__init__.pyo", line 3, in <module>
  File "requests\packages\urllib3__init__.pyo", line 16, in <module>
  File "requests\packages\urllib3\connectionpool.pyo", line 39, in <module>
  File "requests\packages\urllib3\request.pyo", line 12, in <module>
  File "requests\packages\urllib3\filepost.pyo", line 15, in <module>
  File "requests\packages\urllib3\fields.pyo", line 7, in <module>
ImportError: No module named email.utils

When using script no idea where dosage is installing in order to use properly, can't seem to find it in any normal directories.

I am basically a python/github noob so i apologize if this is not the right place to log this or you have already fixed these issues.  If so is there a detailed tutorial available on how to install and run properly.

Thank You

**Comment by TobiX** [comment]
Yes, sorry, this is a known issue (already reported as wummel#82) - Your best bet currently is to use the development version, which isn't trivial to get running on Windows... I'll try to get a guide together.

**Comment by developerinthedark** [comment]
Uhm. It was quite trivial to install it actually. 

The following steps installed it.
git clone https://github.com/webcomics/dosage.git 
cd dosage
pip install -e .

I did do the step of "pip install twine", but I am not sure if that is relevant.
 (It was on the package page, were I got the "pip install -e ." command from)
I do have python and git installed. And in my Path.

**Comment by dbb1480** [comment]
Hi developerinthedark

I installed GIT and added it to my path, however when i run the git clone command I get this response.

fatal: could not create work tree dir 'dosage': Permission denied

i guess how do i get the permission to dosage.git

**Comment by developerinthedark** [comment]
You appear to be trying to do it in a folder you do not have permissions for. 
Like a program files folder. 

Try it in a different folder. (Or open a command line as an administrator/root)

**Comment by dbb1480** [comment]
you were right about the systems admin cmd prompt, but when i run the pip install -e it is saying i need an options requirement for the argument, what option would that be?

Sorry about all the questions, I am a python noob, and I literally get 5 minutes a night to work on stuff like this.

**Comment by TobiX** [comment]
Basically, the installation goes something like this:

1. Install [Python 3.5.1](https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe)
2. Update pip: ```py -m pip install --upgrade pip```
3. Install LXML from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml: ```pip install lxml-3.6.0-cp35-cp35m-win32.whl```
4. Get dosage git: ```git clone https://github.com/webcomics/dosage.git```
5. Go to dosage dir: ```cd dosage```
6. Install dosage in Development mode: ```pip install -e .[css]``` (The dot is crucial!)

Whenever you want the lastest version, just do a ```git pull``` in the dosage directory...

(Or just use the untested binary from https://buildbox.23.gs/jenkins/job/Dosage-Bin/)

**Comment by dbb1480** [comment]
THAT WORKED!!

THANK YOU BOTH!!

**Comment by xandora** [comment]
For what it's worth, I installed using all the steps here, and it still didn't work (received the same error about email.utils). I ended up having to rename the `dosage` file to `dosage.py`, and only after that would it run correctly.

**Comment by TobiX** [comment]
@xandora If you are getting the same error as before, you are probably still running the old binary - That error cannot happen if you are running from a development version.

**Comment by xandora** [comment]
That’s the thing though, I freshly installed through a git pull, not the old binary.

**Comment by TobiX** [comment]
Version 2.16 should work under Windows again: https://github.com/webcomics/dosage/releases/download/2.16/dosage.exe
