### ISSUE TITLE
DogHouseDiaries broken.

### ISSUE THREAD

**Issue by MrHappy** [webcomics/dosage#5]
Looks like the url has changed...
Now it is: http://thedoghousediaries.com/dhdcomics/2015-04-13.png

**Comment by Manabi** [comment]
PHDComics is till working fine for me, the URL you gave is for DogHouseDiaries.  I've renamed this issue and we'll look into fixing that comic.  If that's not the one you meant, let us know.

**Comment by MrHappy** [comment]
I meant DogHouseDiaries indeed.... That's what you get when you're (trying to) multitask(ing)

**Comment by Manabi** [comment]
Not a problem, it's fixed now in f3abbae.

**Comment by MrHappy** [comment]
That was fast.. Thanks!
