### ISSUE TITLE
Dilbert download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#56]
As stated in #55 

    ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/\\d+-\\d+-\\d+/)"[^>]*STR_Prev[^>]*>'] not found at URL http://dilbert.com/.

**Comment by TobiX** [comment]
Fixed in 2.16.
