### ISSUE TITLE
SandraAndWooGerman download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#58]
As stated in #55
I think this affects the non-german version of Sandra And Woo as well

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http\\:\\/\\/www\\.sandraandwoo\\.com\\/woode\\/comics/\\d+-\\d+-\\d+-[^"]+)"[^>]*[^>]*>'] not found at URL http://www.sandraandwoo.com/woode/.

**Comment by TobiX** [comment]
Fixed in 2.16.
