### ISSUE TITLE
xkcd download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#59]
As stated in #55

     ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http://imgs\\.xkcd\\.com/comics/[^"]+)"[^>]*[^>]*>'] not found at URL http://xkcd.com/1742/.

**Comment by TobiX** [comment]
Fixed in 2.16.
