### ISSUE TITLE
AhoiPolloi download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#60]
As stated in #55

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(/static/antville/ahoipolloi/images/[^"]+)"[^>]*[^>]*>'] not found at URL http://ahoipolloi.blogger.de/.

**Comment by TobiX** [comment]
Fixed in 2.16.
