### ISSUE TITLE
GaiaGerman download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#61]
As stated in #55

I think this could affect the non-german version of Gaia as well

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http\\:\\/\\/www\\.sandraandwoo\\.com\\/gaiade\\/comics/\\d+-\\d+-\\d+-[^"]+)"[^>]*[^>]*>'] not found at URL http://www.sandraandwoo.com/gaiade/.

**Comment by TobiX** [comment]
Fixed in 2.16.
