### ISSUE TITLE
LookingForGroup download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#64]
As stated in #55

    ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(http\\:\\/\\/www\\.lfgcomic\\.com\\/page/[-0-9]+/)"[^>]*feature-item-link[^>]*>'] not found at URL http://www.lfgcomic.com/.

**Comment by TobiX** [comment]
Fixed in 2.16.
