### ISSUE TITLE
Ruthe download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#65]
As stated in #55

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(cartoons/strip_\\d+[^"]+)"[^>]*[^>]*>'] not found at URL http://ruthe.de/.

**Comment by TobiX** [comment]
Fixed in 2.16.
