### ISSUE TITLE
Arcamax download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#66]
As stated in #55
This is an example for all Arcamax webcomics which fail with similar errors

    ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/newspics/[^"]+)"[^>]*zoom[^>]*>'] not found at URL http://www.arcamax.com/thefunnies/babyblues/.

**Comment by TobiX** [comment]
Fixed in 2.16.
