### ISSUE TITLE
DieFruehreifen download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#67]
As stated in #55

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(strips/[F,f]rueh[_]?[S,s]trip_\\d+.jpg)"[^>]*[^>]*>'] not found at URL http://www.die-fruehreifen.de/index.php.

**Comment by TobiX** [comment]
Fixed in 2.16.
