### ISSUE TITLE
JohnnyWander download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#68]
As stated in #55 

    ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http://www\\.johnnywander\\.com/files/comics/[^"]+)"[^>]*[^>]*>'] not found at URL http://www.johnnywander.com/.

**Comment by TobiX** [comment]
Fixed in 2.16.
