### ISSUE TITLE
PennyArcade download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#69]
As stated in #55 

    ERROR: Patterns ['<\\s*[aA]\\s+[^>]*btnPrev[^>]*\\s+[hH][rR][eE][fF]\\s*=\\s*"(http\\:\\/\\/penny\\-arcade\\.com\\/comic\\/[^"]+)"[^>]*[^>]*>'] not found at URL http://penny-arcade.com/comic/.

**Comment by TobiX** [comment]
Fixed in 2.16.
