### ISSUE TITLE
Wolffmorgenthaler download fails

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#71]
As stated in #55 

    ERROR: Patterns ['<\\s*[dD][iI][vV]\\s+(?:[^>]*\\s+)?[cC][lL][aA][sS][sS]\\s*=\\s*"box-content"[^>]*[^>]*>\\s*<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"[^"]+"[^>]*[^>]*>\\s*<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http://kindofnormal\\.com/img/wumo/\\d+/\\d+/[^/"]+)"[^>]*[^>]*>'] not found at URL http://kindofnormal.com/wumo/.

**Comment by TobiX** [comment]
That module does not exist in 2.16 anymore.
