### ISSUE TITLE
Whomp download fails

### ISSUE THREAD

**Issue by nonamethanks** [webcomics/dosage#75]
```
[~/dosage] > dosage whomp --all
Whomp> Retrieving all strips
Whomp> Skipping existing file "Comics/Whomp/1482121824-2016-12-19-The-Fray-Of-The-Dodo.jpg".
Whomp> WARN: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(http\\:\\/\\/www\\.whompcomic\\.com\\/\\d+/\\d+/\\d+/[^"]+)"[^>]*navi-prev[^>]*>'] not found at URL http://www.whompcomic.com/. Assuming no previous comic strips exist.

```

**Comment by TobiX** [comment]
This is fixed in the current development snapshot.

**Comment by nonamethanks** [comment]
Where can I find that snapshot? Or will I have to wait until it's pushed to github?

**Comment by TobiX** [comment]
Should be in master, that pattern in your bug report isn't in the code anymore...

**Comment by nonamethanks** [comment]
@TobiX 


`[~] > rm -rf dosage

[~] > git clone https://github.com/webcomics/dosage.git 
Cloning into 'dosage'...
remote: Counting objects: 108773, done.
remote: Total 108773 (delta 0), reused 0 (delta 0), pack-reused 108773
Receiving objects: 100% (108773/108773), 25.60 MiB | 295.00 KiB/s, done.
Resolving deltas: 100% (104780/104780), done.

[~] > cd dosage 

[~/dosage] > dosage whomp --all
Whomp> Retrieving all strips
Whomp> Saved Comics/Whomp/1482730916-2016-12-26-Merry-Christmas.jpg (130.04KB).
Whomp> WARN: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(http\\:\\/\\/www\\.whompcomic\\.com\\/\\d+/\\d+/\\d+/[^"]+)"[^>]*navi-prev[^>]*>'] not found at URL http://www.whompcomic.com/. Assuming no previous comic strips exist.
`
