### ISSUE TITLE
Cannot install with `pip install git+https://github.com/webcomics/dosage`

### ISSUE THREAD

**Issue by sphh** [webcomics/dosage#81]
I installed dosage as root with `pip install git+https://github.com/webcomics/dosage` as suggested in #80, but pip failed. This is pip's log file: [pip.log](https://github.com/webcomics/dosage/files/768914/pip.log.txt)

System:
Debian 8.7
Python 2.7.9
pip 9.0.1

**Comment by TobiX** [comment]
Unfortunatly, setuptools in Debian stable is too old to install the current development version (see the [setup.py](https://github.com/webcomics/dosage/blob/master/setup.py#L12) for minimum requirements). AFAICS, installing `python-setuptools` (or `python3-setuptools`) from Backports is enough to get Dosage installed.

PS1: Using `--user` with `pip install` lets you install dosage without being root (just add `$HOME/.local/bin` to your path)
PS2: Install `python-lxml` (or `python3-lxml`) before, so installing dosage doesn't need a C compiler

**Comment by sphh** [comment]
Hi Toby!

Thanks. After upgrading `setuptools` with pip, I got it installed! Great! (That was a good tip with `python-lxml`...) I also installed it on a Linux Mint 18.1 system and Python 3.x without any problem.

Just a thought: Wouldn't it be a good idea to include this information into the README file?

Thank you for your help.
