### ISSUE TITLE
XKCD not retrieving, giving SSL error

### ISSUE THREAD

**Issue by HGPunk** [webcomics/dosage#82]
I'm looking to download some comics, but whenever I try to retrieve XKCD, I get this message:

`ERROR: URL retrieval of http://xkcd.com/ failed: [Errno 185090050] _ssl.c:343: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib`

I'm guessing it has something to do with xkcd,com's SSL, but how do I fix it?

**Comment by TobiX** [comment]
Your Python/requests/SSL installation seems to be broken. 

See
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification (& http://docs.python-requests.org/en/latest/user/advanced/#ca-certificates) for the required setup.
