### ISSUE TITLE
Resume support

### ISSUE THREAD

**Issue by za3k** [webcomics/dosage#83]
Right now, when I download a comic with `--all`, it often fails midway for various reasons. It would be nice to have `--all` and `-N` support resuming from a specific URL, or a previous failed download, so re-running with `--all` doesn't traverse the entire website up to that point.

**Comment by za3k** [comment]
OK, thought about this a little more, and maybe what's wanted even more is better retry support to begin with (independent of the plugin).

**Comment by TobiX** [comment]
Currently, dosage doesn't keep any state between runs. You can manually resume from a specific comic by using the comicname:id syntax (see `dosage -m xkcd` for the exact index syntax per comic). Re-runnig with -a always traverses the whole comic site, without re-downloading the image files.

Resuming from an arbitrary point is on my todo list, but pretty hard with dosage's current design...

**Comment by DavidAccola** [comment]
> OK, thought about this a little more, and maybe what's wanted even more is better retry support to begin with (independent of the plugin).

What plugin is this talking about? I'm having some issues with a site giving sporadic 500s, but no issue later. If there's a way to make dosage retry I'm interested.

**Comment by za3k** [comment]
Sorry, it's been five years since I reported this. I don't even remember what dosage is any more.

**Comment by TobiX** [comment]
@DavidAccola Please open a new issue instead of hijacking age-old issues - I'm tracking the general idea of "resuming" as issue #261 (for the record, dosage has a bit of "retrying" logic already, since it is build on python requests, but nothing on a more "global" scale)

@za3k Sorry for the noise, closing the issue.
