### ISSUE TITLE
Gocomics fails

### ISSUE THREAD

**Issue by lytsabr** [webcomics/dosage#86]
Dosage is no longer downloading Gocomics images.

The error is (9ChickweedLane is the example):
GoComics/9ChickweedLane> ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/[^"]+/\\d+/\\d+/\\d+)"[^>]*prev[^>]*>'] not found at URL http://www.gocomics.com/9chickweedlane.

There no longer is an A HREF in gocomics, so this is failing on that -- and I cannot find in the code where [hH][rR][eE][fF] is being called...

Thanks!

**Comment by TobiX** [comment]
Please use a current git snapshot, this is already fixed. See #81 for some ideas how to install newer versions.
