### ISSUE TITLE
8-bit-theater broken?

### ISSUE THREAD

**Issue by ev1l0rd** [webcomics/dosage#87]
Installed dosage using `sudo pip install dosage`. Running Ubuntu 17.04.

I get the following error when trying to run dosage to download 8BitTheater (listed in dosage as NuklearPower/8BitTheater). If you need any other output, feel free to ask.

````bash
ev1l0rd@ev1l0rd:~$ dosage NuklearPower/8BitTheater
NuklearPower/8BitTheater> Retrieving 1 strip
NuklearPower/8BitTheater> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*
=\\s*"(http://v\\.cdn\\.nuklearpower\\.com/comics/[^"]+)"[^>]*[^>]*>'] not found at URL http://
www.nuklearpower.com/8-bit-theater/.
````

**Comment by TobiX** [comment]
This is already fixed in master. See #81 for some ideas how to install newer versions.
