### ISSUE TITLE
Remove descriptions?

### ISSUE THREAD

**Issue by TobiX** [webcomics/dosage#9]
Some comics have some description text in our code. It's pretty useless for the general operation of Dosage itself and I would like to remove all descriptions (and all related code). Comments?

**Comment by Manabi** [comment]
The descriptions are given when you do dosage -m, and could be useful if you're trying to figure out what a comic is about.  But I wonder if anyone uses dosage that way?  Personally I use it for comics I'm already reading and discover new comics through other sources.  Then I just do `dosage --list | grep comicname` to see if it's already in dosage or not.

So I don't see any real need for it, but I don't think it's hurting anything either.  I guess I'm neutral on it.

**Comment by Null000** [comment]
I'm for removal as it simplifies things and don't think anyone will miss them.
