### ISSUE TITLE
WebComic 1997

### ISSUE THREAD

**Issue by AnJoMi** [webcomics/dosage#93]
New user, I know less about python than I do about....well, something I know almost nothing about. Setting it up using copy and paste from various websites (installing python/pip/etc...
My environment variables aren't set right yet, but it works.
Getting an error trying to get the webcomic 1997. Here's a copy/paste.

C:\>C:\Users\Q\AppData\Local\Programs\Python\Python36-32\python C:\Users\Q\AppData\Local\Programs\Python\Python36-32\scripts\dosage 1997
1997> Retrieving 1 strip
1997> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http\\:\\/\\/1977thecomic\\.com\\/comics-1977/[^"]+)"[^>]*[^>]*>'] not found at URL http://1977thecomic.com/.

C:\>C:\Users\Q\AppData\Local\Programs\Python\Python36-32\python C:\Users\Q\AppData\Local\Programs\Python\Python36-32\scripts\dosage 1997 --all
1997> Retrieving all strips
1997> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http\\:\\/\\/1977thecomic\\.com\\/comics-1977/[^"]+)"[^>]*[^>]*>'] not found at URL http://1977thecomic.com/.
1997> WARN: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"([^"]+)"[^>]*[^>]*>Previous'] not found at URL http://1977thecomic.com/. Assuming no previous comic strips exist.
 

I pulled up the website and the comic is still there.
Here's one I used just to make sure it was functional.

C:\>C:\Users\Q\AppData\Local\Programs\Python\Python36-32\python C:\Users\Q\AppData\Local\Programs\Python\Python36-32\scripts\dosage AGirlAndHerFed
AGirlAndHerFed> Retrieving 1 strip
AGirlAndHerFed> Saved Comics\AGirlAndHerFed\1-1532.jpg (135.59KB).

Also, a question.
If a new version is made, do I need to manually update? Do I just use the same pip command I used to install it?

Thanks for your time, and sorry for being a 'noob'

**Comment by TobiX** [comment]
Please just use the dev build from here: https://buildbox.23.gs/jenkins/job/Dosage-Win32/ - That comic has been fixed a while ago...
