### ISSUE TITLE
Both FoxTrot and FoxTrotClassic fail

### ISSUE THREAD

**Issue by JohnBlood** [webcomics/dosage#94]
When I try to download the latest Foxtrot, I get this error:

`GoComics/FoxTrot> ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/[^"]+/\\d+/\\d+/\\d+)"[^>]*prev[^>]*>'] not found at URL http://www.gocomics.com/foxtrot.`

When I try to download the lastest FoxtrotClassic, I get this error: 

`GoComics/FoxTrotClassics> ERROR: Patterns ['<\\s*[aA]\\s+(?:[^>]*\\s+)?[hH][rR][eE][fF]\\s*=\\s*"(/[^"]+/\\d+/\\d+/\\d+)"[^>]*prev[^>]*>'] not found at URL http://www.gocomics.com/foxtrotclassics.`

**Comment by TobiX** [comment]
This has already been fixed in the development version, try either the Windows build from https://buildbox.23.gs/jenkins/job/Dosage-Win32/ or install the development version via pip (see #81 for some pointers).
