### ISSUE TITLE
Gaia stopped downloading

### ISSUE THREAD

**Issue by xandora** [webcomics/dosage#98]
Throws an error when attempting to download:

`Gaia> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http\\:\\/\\/www\\.sandraandwoo\\.com\\/gaia\\/comics/\\d+-\\d+-\\d+-[^"]+)"[^>]*[^>]*>'] not found at URL http://www.sandraandwoo.com/gaia/2013/10/08/the-tower-in-the-sky-043/.`

Page URL:
http://www.sandraandwoo.com/gaia/2011/11/01/cover/

Image URL:
http://www.sandraandwoo.com/gaia/comics/2011-11-01-cover.jpg

**Comment by TobiX** [comment]
This is already fixed in the latest development version, please see #81 on how to install development versions (or take the Windows binary from my build server: https://buildbox.23.gs/jenkins/job/Dosage-Win32/)
